<?php

class PurchaseForm extends CFormModel
{
	public $id;
	public $order_user;
	//public $technician;
    public $status;
    public $remark;
	public $luu;
	public $lcu;
	public $statusList;
	public $order_code;
	public $order_class;
	public $activity_id;
	public $goods_list;

	public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->status = "pending";
        $this->goods_list = array(
            array(
                "id"=>"",
                "goods_id"=>"",
                "classify_id"=>"",
                "stickies_id"=>"",
                "note"=>"",
                "name"=>"",
                "type"=>"",
                "unit"=>"",
                "price"=>"",
                "goods_num"=>"",
                "confirm_num"=>"",
                "remark"=>"",
            )
        );
    }

    public function attributeLabels()
	{
		return array(
            'order_code'=>Yii::t('procurement','Order Code'),
            'order_class'=>Yii::t('procurement','Order Class'),
            'activity_id'=>Yii::t('procurement','Order of Activity'),
            'goods_list'=>Yii::t('procurement','Goods List'),
            'order_user'=>Yii::t('procurement','Order User'),
            //'technician'=>Yii::t('procurement','Technician'),
            'status'=>Yii::t('procurement','Order Status'),
            'remark'=>Yii::t('procurement','Remark'),
		);
	}

	/**
	 * Declares the validation rules.
	 */
	public function rules()
	{
		return array(
			array('id, order_code, order_user, order_class, activity_id, technician, status, remark, luu, lcu, lud, lcd','safe'),
            array('goods_list','required','on'=>array('audit','edit','reject')),
            array('goods_list','validateGoods','on'=>array('audit','edit')),
            array('remark','required','on'=>'reject'),
            //array('order_num','numerical','allowEmpty'=>true,'integerOnly'=>true),
            //array('order_num','in','range'=>range(0,600)),
		);
	}

	//驗證訂單內的物品
    public function validateGoods($attribute, $params){
	    $goods_list = $this->goods_list;
        if(count($this->goods_list)<1){
            $message = Yii::t('procurement','Fill in at least one goods');
            $this->addError($attribute,$message);
            return false;
        }
        $validateList = array();
        foreach ($goods_list as $key =>$goods){
            if(empty($goods["goods_id"]) && empty($goods["confirm_num"])){
                unset($this->goods_list[$key]);
            }else if (empty($goods["confirm_num"]) && $goods["confirm_num"] != 0){
                $message = Yii::t('procurement','Actual Number cannot be empty');
                $this->addError($attribute,$message);
                return false;
            }else if(!is_numeric($goods["confirm_num"]) || floor($goods["confirm_num"])!=$goods["confirm_num"]){
                $message = Yii::t('procurement','Actual Number can only be numbered');
                $this->addError($attribute,$message);
                return false;
            }else{
                $list = OrderForm::getOneGoodsToId($goods["goods_id"],$this->order_class);
                if (empty($list)){
                    $message = Yii::t('procurement','Not Font Goods').$goods["name"];
                    $this->addError($attribute,$message);
                    return false;
                }else{
                    if(empty($list["rules_id"])){
                        //常規驗證
                        if (intval($goods["confirm_num"])%intval($list["multiple"]) != 0){
                            $message = $list["name"]." ".Yii::t('procurement','Multiple is').$list["multiple"];
                            $this->addError($attribute,$message);
                            return false;
                        }elseif (intval($list["big_num"])<intval($goods["confirm_num"])){
                            $message = $list["name"]." ".Yii::t('procurement','Max Number is').$list["big_num"];
                            $this->addError($attribute,$message);
                            return false;
                        }elseif (intval($list["small_num"])>intval($goods["confirm_num"])){
                            $message = $list["name"]." ".Yii::t('procurement','Min Number is').$list["small_num"];
                            $this->addError($attribute,$message);
                            return false;
                        }
                    }else{
                        //混合驗證
                        if(empty($validateList[$list["rules_id"]])){
                            $rules = RulesForm::getRulesToId($list["rules_id"]);
                            $validateList[$list["rules_id"]] = array(
                                "rulesName"=>$rules["name"],
                                "rulesMultiple"=>$rules["multiple"],
                                "rulesMin"=>$rules["min"],
                                "rulesMax"=>$rules["max"],
                                "goodsNum"=>0,
                            );
                        }
                        $validateList[$list["rules_id"]]["goodsNum"]+=intval($goods["confirm_num"]);
                    }
                }
            }
        }
        foreach ($validateList as $hybrid){
            if (intval($hybrid["goodsNum"])%intval($hybrid["rulesMultiple"]) != 0){
                $message = $hybrid["rulesName"]." ".Yii::t('procurement','Multiple is').$hybrid["rulesMultiple"];
                $this->addError($attribute,$message);
                return false;
            }elseif (intval($hybrid["rulesMax"])<intval($hybrid["goodsNum"])){
                $message = $hybrid["rulesName"]." ".Yii::t('procurement','Max Number is').$hybrid["rulesMax"];
                $this->addError($attribute,$message);
                return false;
            }elseif (intval($hybrid["rulesMin"])>intval($hybrid["goodsNum"])){
                $message = $hybrid["rulesName"]." ".Yii::t('procurement','Min Number is').$hybrid["rulesMin"];
                $this->addError($attribute,$message);
                return false;
            }
        }
        if(count($this->goods_list)<1){
            $message = Yii::t('procurement','Fill in at least one goods');
            $this->addError($attribute,$message);
        }
    }


	public function retrieveData($index) {
		$city = Yii::app()->user->city();
		$rows = Yii::app()->db->createCommand()->select("id, order_code, lcu, order_class, order_user, technician, status, remark, activity_id")
            ->from("opr_order")->where("id=:id AND judge=1",array(":id"=>$index))->queryAll();
		if (count($rows) > 0) {
			foreach ($rows as $row) {
                $this->id = $row['id'];
                $this->order_code = $row['order_code'];
                $this->order_class = $row['order_class'];
                $this->activity_id = $row['activity_id'];
                $this->lcu = $row['lcu'];
                $this->goods_list = OrderForm::getGoodsListToId($row['id']);
                $this->order_user = $row['order_user'];
                //$this->technician = $row['technician'];
                $this->status = $row['status'];
                $this->remark = "";
                $this->statusList = OrderForm::getStatusListToId($row['id']);
                break;
			}
		}
		return true;
	}
    //整理出下載的物品列表
    public function resetGoodsList(){
        $goodsList = $this->goods_list;
        foreach ($goodsList as $key=>$goods){
            $multiple = $goodsList[$key]["multiple"];
            $multiple = intval($multiple);
            unset($goodsList[$key]["id"]);
            unset($goodsList[$key]["goods_id"]);
            unset($goodsList[$key]["classify_id"]);
            switch ($this->order_class){
                case "Domestic":
                    $goodsList[$key]["stickies_id"] = $this->getStickiesToId($goodsList[$key]["stickies_id"]);
                    $goodsList[$key]["total"] = sprintf("%.2f",floatval($goodsList[$key]["price"])*intval($goodsList[$key]["confirm_num"]));
                    break;
                case "Import":
                    unset($goodsList[$key]["stickies_id"]);
                    $goodsList[$key]["total"] = sprintf("%.2f",floatval($goodsList[$key]["price"])*intval($goodsList[$key]["confirm_num"]));
                    $sum = floatval($goodsList[$key]["net_weight"])*intval($goodsList[$key]["confirm_num"])/$multiple;
                    $goodsList[$key]["total2"] = round($sum,2);
                    $sum = floatval($goodsList[$key]["gross_weight"])*intval($goodsList[$key]["confirm_num"])/$multiple;
                    $goodsList[$key]["total3"] = round($sum,2);
                    $volume = explode('×',$goodsList[$key]["LWH"]);
                    $volume = floatval($volume[0])*floatval($volume[1])*floatval($volume[2])/1000000;
                    $sum = $volume*intval($goodsList[$key]["confirm_num"])/$multiple;
                    $goodsList[$key]["total4"] = round($sum,2);
                    break;
                case "Fast":
                    unset($goodsList[$key]["stickies_id"]);
                    $goodsList[$key]["total"] = sprintf("%.2f",floatval($goodsList[$key]["price"])*intval($goodsList[$key]["confirm_num"]));
                    break;
            }
            unset($goodsList[$key]["multiple"]);
        }
        return $goodsList;
    }
    //獲取標籤內容
    public function getStickiesToId($index) {
        $rows = Yii::app()->db->createCommand()->select("content")
            ->from("opr_stickies")->where("id=:id",array(":id"=>$index))->queryAll();
        if ($rows) {
            return $rows[0]['content'];
        }
        return "";
    }

    //獲取表格的头
    public function getTableHeard(){
        $arr = array("物品編號","物品名称","物品規格","物品單位");
        switch ($this->order_class){
            case "Import":
                array_push($arr,'物品單價（US$）');
                array_push($arr,"净重（kg）");
                array_push($arr,"毛重（kg）");
                array_push($arr,"長×寬×高（cm）");
                array_push($arr,"要求數量");
                array_push($arr,"實際數量");
                array_push($arr,"要求備註");
                array_push($arr,"總部備註");
                array_push($arr,'總價（US$）');
                array_push($arr,'總淨重（kg）');
                array_push($arr,'總毛重（kg）');
                array_push($arr,'總體積（m³）');
                break;
            case "Domestic":
                array_push($arr,"物品單價（RMB）");
                array_push($arr,"物品標籤");
                array_push($arr,"要求數量");
                array_push($arr,"實際數量");
                array_push($arr,"要求備註");
                array_push($arr,"總部備註");
                array_push($arr,"總價（RMB）");
                break;
            case "Fast":
                array_push($arr,'物品單價（US$）');
                array_push($arr,"要求數量");
                array_push($arr,"實際數量");
                array_push($arr,"要求備註");
                array_push($arr,"總部備註");
                array_push($arr,'總價（US$）');
                break;

        }
        return $arr;
    }
	
	public function saveData()
	{
		$connection = Yii::app()->db;
		$transaction=$connection->beginTransaction();
		try {
			$this->saveGoods($connection);
			$transaction->commit();
		}
		catch(Exception $e) {
			$transaction->rollback();
			throw new CHttpException(404,'Cannot update. ('.$e->getMessage().')');
		}
	}

	protected function saveGoods(&$connection) {
        $oldOrderStatus = Yii::app()->db->createCommand()->select()->from("opr_order")
            ->where("id=:id",array(":id"=>$this->id))->queryAll();
		$sql = '';
        switch ($this->scenario) {
            case 'edit':
                $sql = "update opr_order set
							remark = :remark,
							luu = :luu,
							lud = :lud,
							status = :status
						where id = :id AND judge=1
						";
                $this->status = "read";
                break;
            case 'audit':
                $sql = "update opr_order set
							remark = :remark,
							luu = :luu,
							lud = :lud,
							status = :status
						where id = :id AND judge=1
						";
                $this->status = "approve";
                break;
            case 'reject':
                $sql = "update opr_order set
							remark = :remark,
							luu = :luu,
							lud = :lud,
							status = :status
						where id = :id AND judge=1
						";
                $this->goods_list = array();
                $this->status = "reject";
                break;
        }
		if (empty($sql)) return false;

        $city = Yii::app()->user->city();
        $uid = Yii::app()->user->id;
        $order_username = Yii::app()->user->name;
        $command=$connection->createCommand($sql);
        if (strpos($sql,':id')!==false)
            $command->bindParam(':id',$this->id,PDO::PARAM_INT);
        if (strpos($sql,':status')!==false){
            $command->bindParam(':status',$this->status,PDO::PARAM_STR);
        }

        if (strpos($sql,':remark')!==false)
            $command->bindParam(':remark',$this->remark,PDO::PARAM_STR);
        if (strpos($sql,':lud')!==false)
            $command->bindParam(':lud',date('Y-m-d H:i:s'),PDO::PARAM_STR);
        if (strpos($sql,':luu')!==false)
            $command->bindParam(':luu',$uid,PDO::PARAM_STR);
        $command->execute();

        Yii::app()->db->createCommand()->insert('opr_order_status', array(
            'order_id'=>$this->id,
            'status'=>$this->status,
            'r_remark'=>$this->remark,
            'lcu'=>$order_username,
            'time'=>date('Y-m-d H:i:s'),
        ));

        //物品的添加、修改
        foreach ($this->goods_list as $goods){
            if(!empty($goods["id"])){
                //修改
                Yii::app()->db->createCommand()->update('opr_order_goods', array(
                    'confirm_num'=>$goods["confirm_num"],
                    'remark'=>$goods["remark"],
                    'luu'=>$uid,
                    'lud'=>date('Y-m-d H:i:s'),
                ), 'id=:id', array(':id'=>$goods["id"]));
            }
        }


        //發送郵件
        OrderGoods::sendEmail($oldOrderStatus,$this->status,$this->order_code,$this->activity_id);
		return true;
	}
	//退回
	function backward(){
        $rows = Yii::app()->db->createCommand()->select("id")->from("opr_order")->where('status = "approve" and id = :id',array(':id'=>$this->id))->queryAll();
        if(count($rows) > 0){
            $uid = Yii::app()->user->id;
            $this->status = "sent";
            Yii::app()->db->createCommand()->update('opr_order', array(
                'status'=>$this->status,
                'remark'=>$this->remark,
                'luu'=>$uid,
                'lud'=>date('Y-m-d H:i:s'),
            ), 'id=:id', array(':id'=>$this->id));

            Yii::app()->db->createCommand()->insert('opr_order_status', array(
                'order_id'=>$this->id,
                'status'=>"backward",
                'r_remark'=>$this->remark,
                'lcu'=>$uid,
                'time'=>date('Y-m-d H:i:s'),
            ));
            return true;
        }
        return false;
    }

}
